@startuml
class LevelTimer {
    + maxTime : float
    + Setup(newMaxTime:float) : void
    + Update() : void
}
class "ScriptableObjectSingleton"<T> {
}
"ScriptableObjectSingleton" "<LevelTimer>" <|-- LevelTimer
@enduml
