@startuml
class PlayerData {
    + <<override>> Load() : IEntity
}
LevelDataEntity <|-- PlayerData
PlayerData --> "camera" FirstPersonCamera
PlayerData --> "movementController" FirstPersonMovement
PlayerData --> "gunLevelData" GunLevelData
@enduml
