@startuml
!include .\\Assets\Scripts\Game.puml
!include .\\Assets\Scripts\Timer.puml
!include .\\Assets\Scripts\DamageTakingLogics\DamageData.puml
!include .\\Assets\Scripts\DamageTakingLogics\DamageType.puml
!include .\\Assets\Scripts\DamageTakingLogics\DamageTypeDecorator.puml
!include .\\Assets\Scripts\DamageTakingLogics\DamageTypeLookup.puml
!include .\\Assets\Scripts\DamageTakingLogics\IDamagable.puml
!include .\\Assets\Scripts\DamageTakingLogics\IDamager.puml
!include .\\Assets\Scripts\Entity\EntityManager.puml
!include .\\Assets\Scripts\Entity\IEntity.puml
!include .\\Assets\Scripts\GeneralUI\ColorExtensions.puml
!include .\\Assets\Scripts\GeneralUI\LevelTimer.puml
!include .\\Assets\Scripts\GeneralUI\PlayerInterfaceConsole.puml
!include .\\Assets\Scripts\GeneralUI\TextPrefab.puml
!include .\\Assets\Scripts\Guns\Gun.puml
!include .\\Assets\Scripts\Guns\GunBuilder.puml
!include .\\Assets\Scripts\Guns\GunHandler.puml
!include .\\Assets\Scripts\Guns\GunLevelData.puml
!include .\\Assets\Scripts\Guns\GunLookup.puml
!include .\\Assets\Scripts\Level\LevelData.puml
!include .\\Assets\Scripts\Level\LevelDataEntity.puml
!include .\\Assets\Scripts\Level\LevelManager.puml
!include .\\Assets\Scripts\Objectpooling\IPoolable.puml
!include .\\Assets\Scripts\Objectpooling\Objectpool.puml
!include .\\Assets\Scripts\Singletons\ScriptableObjectSingleton.puml
!include .\\Assets\Scripts\Singletons\SingletonBehaviour.puml
!include .\\Assets\Scripts\Entity\CollisionTriggers\HurtTriggerData.puml
!include .\\Assets\Scripts\Entity\CollisionTriggers\HurtTriggerEntity.puml
!include .\\Assets\Scripts\Entity\CollisionTriggers\TriggerEntity.puml
!include .\\Assets\Scripts\Entity\DataComponents\HealthData.puml
!include .\\Assets\Scripts\Entity\DataComponents\HealthSystem.puml
!include .\\Assets\Scripts\Entity\Enemies\EnemyData.puml
!include .\\Assets\Scripts\Entity\Enemies\EnemyEntity.puml
!include .\\Assets\Scripts\Entity\Particles\BulletLineEntity.puml
!include .\\Assets\Scripts\Entity\Player\FirstPersonCamera.puml
!include .\\Assets\Scripts\Entity\Player\FirstPersonMovement.puml
!include .\\Assets\Scripts\Entity\Player\PlayerData.puml
!include .\\Assets\Scripts\Entity\Player\PlayerEntity.puml
!include .\\Assets\Scripts\Entity\Projectiles\ProjectileBuilder.puml
!include .\\Assets\Scripts\Entity\Projectiles\ProjectileEntity.puml
!include .\\Assets\Scripts\Guns\ShootStrategies\IShootStrategy.puml
!include .\\Assets\Scripts\Guns\ShootStrategies\ProjectileShootStrategy.puml
!include .\\Assets\Scripts\Guns\ShootStrategies\RaycastShootStrategy.puml
!include .\\Assets\Scripts\Guns\ShootStrategies\ShootData.puml
!include .\\Assets\Scripts\Guns\UI\GunInventoryItemUI.puml
!include .\\Assets\Scripts\Guns\UI\GunInventoryUI.puml
@enduml
