@startuml
class KeyPickupEntity {
    + Setup() : void
    + <<override>> OnEnableObject() : void
    + <<override>> OnDisableObject() : void
}
TriggerEntity <|-- KeyPickupEntity
KeyPickupEntity --> "doorEntity" DoorEntity
@enduml
